# This is a workflow to build, push and deploy a Docker image to Kubernetes

name: CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job to build and push Docker image
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: anishanniz/test-cesi-web-app
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=pr
            latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=anishanniz/test-cesi-web-app:latest
          cache-to: type=inline

  # Job to deploy to Kubernetes
  deploy-on-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      
      - name: Deploy to Kubernetes
        run: |
          # Update image tag in deployment file if needed
          TAG=$(echo $GITHUB_SHA | head -c7)
          sed -i "s|anishanniz/test-cesi-web-app:.*|anishanniz/test-cesi-web-app:$TAG|" ./k8s/deployment.yaml
          
          # Apply Kubernetes manifests
          kubectl apply -f ./k8s/
          
          # Verify deployment
          kubectl rollout status deployment/test-cesi-web-app -n default
